import os
import asyncio
import streamlit as st
from sql_agent import run_sql_agent

# 1. Page Configuration
st.set_page_config(
    page_title="AI Data Analyst",
    page_icon="📊",
    layout="wide"
)

# 2. Sidebar Configuration
st.sidebar.title("⚙️ Agent Status")
st.sidebar.success("Cloud Engine Ready")

st.sidebar.markdown("---")
st.sidebar.subheader("💡 Sample Prompts")
st.sidebar.markdown(
    """
    * *'What are the total sales per region? Plot a chart for it.'*
    * *'Which category generated the highest revenue?'*
    * *'Show total sales count for Furniture.'*
    """
)

# 3. Main Dashboard Header
st.title("📊 AI Data Analyst")
st.write("Ask natural language questions about your company database in real-time.")

# 4. Initialize Session State for Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display previous messages in chat container
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])
        if "image" in message and os.path.exists(message["image"]):
            st.image(message["image"], use_container_width=True)

# 5. User Query Input
user_input = st.chat_input("Type your data query here...")

if user_input:
    # Append & display user message
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.write(user_input)

    # Process Assistant Response
    with st.chat_message("assistant"):
        with st.spinner("Analyzing data..."):
            # Clean up old chart before executing new query
            chart_path = "sales_chart.png"
            if os.path.exists(chart_path):
                try:
                    os.remove(chart_path)
                except Exception:
                    pass

            try:
                # Direct call in Python using Streamlit secrets
                result = asyncio.run(run_sql_agent(user_input))
                final_answer = result.get("final_answer", "No analysis returned.")
                
                st.write(final_answer)
                
                # Check if a chart was generated by the tool
                has_chart = os.path.exists(chart_path)
                if has_chart:
                    st.image(chart_path, use_container_width=True)

                # Save assistant response to session state
                message_data = {"role": "assistant", "content": final_answer}
                if has_chart:
                    message_data["image"] = chart_path
                st.session_state.messages.append(message_data)

            except Exception as e:
                st.error(f"Error executing agent query: {e}")
